import Head from "next/head";
import Avatar from "../components/Avatar";

import { ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
import Footer from "../components/Footer";
import { useRef } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);

  const search = (e) => {
    e.preventDefault();

    const term = searchInputRef.current.value;

    if (!term) return;

    router.push(`/search?term=${term}`);
  };

  return (
    <div className="flex flex-col item-center justify-center h-screen">
      <Head>
        <title>Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex w-full justify-between p-5 text-sm text-gray-700">
        <div className="flex space-x-5 items-center">
          <p className="link">
            <a href="https://www.linkedin.com/in/sai-krishna-das/">About</a>
          </p>
          <p className="link">
            <a href="https://github.com/saikrishnadas/Explorer">Code</a>
          </p>
        </div>
        <div className="flex space-x-5 items-center">
          <p className="link">saikrishnadas666@gmail.com</p>
          <p className="link">
            <a href="https://www.instagram.com/sai_._0000_/">Images</a>
          </p>

          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />

          <Avatar url="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Favatars2.githubusercontent.com%2Fu%2F30836867%3Fs%3D400%26v%3D4&f=1&nofb=1" />
        </div>
      </header>

      <form className="flex flex-col items-center mt-44 flex-grow">
        <img src="/explorerlogowhite.png" alt="logo" height={100} width={300} />
        <div
          className="flex w-full mt-4 hover:shadow-lg focus-within:shadow-lg max-w-md
        rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl"
        >
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input
            ref={searchInputRef}
            type="text"
            className="flex-grow focus:outline-none"
          />
        </div>

        <div className="flex flex-col w-1/4 space-y-2 justify-center mt-8">
          <button className="btn" onClick={search}>
            Search
          </button>
        </div>
      </form>

      <Footer />
    </div>
  );
}
