import Head from "next/head";
import Avatar from "../components/Avatar";

import { SunIcon, MoonIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
import { useRef, useState } from "react";
import { useRouter } from "next/router";
import { LocationMarkerIcon } from "@heroicons/react/solid";

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);
  const [dark, setDark] = useState(false);

  const search = (e) => {
    e.preventDefault();

    const term = searchInputRef.current.value;

    if (!term) return;

    router.push(`/search?term=${term}`);
  };

  return (
    <div
      className={`flex flex-col item-center justify-center h-screen ${
        dark && "bg-gray-800"
      }`}
    >
      <Head>
        <title>Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex w-full justify-between p-5 text-sm text-gray-700">
        <div className="flex space-x-5 items-center">
          <p className={`link ${dark && "text-white"}`}>
            <a href="https://www.linkedin.com/in/sai-krishna-das/">About</a>
          </p>
          <p className={`link ${dark && "text-white"}`}>
            <a href="https://github.com/saikrishnadas/Explorer">Code</a>
          </p>
        </div>

        <div className="flex space-x-5 items-center">
          {dark ? (
            <SunIcon
              className={`themebtn ${dark && "text-white"}`}
              onClick={() => setDark(!dark)}
            />
          ) : (
            <MoonIcon className="themebtn" onClick={() => setDark(!dark)} />
          )}

          <p className={`link ${dark && "text-white"}`}>
            saikrishnadas666@gmail.com
          </p>
          <p className={`link ${dark && "text-white"}`}>
            <a href="https://www.instagram.com/sai_._0000_/">Images</a>
          </p>

          <Avatar url="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Favatars2.githubusercontent.com%2Fu%2F30836867%3Fs%3D400%26v%3D4&f=1&nofb=1" />
        </div>
      </header>

      <form className="flex flex-col items-center mt-44 flex-grow">
        {dark ? (
          <img
            src="/explorerlogodark.png"
            alt="logo"
            height={100}
            width={300}
          />
        ) : (
          <img
            src="/explorerlogowhite.png"
            alt="logo"
            height={100}
            width={300}
          />
        )}

        <div
          className={`flex w-full mt-4 hover:shadow-lg focus-within:shadow-lg max-w-md
        rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl ${
          dark && "border-black-200"
        }`}
        >
          <SearchIcon className="h-5 mr-3 text-gray-500 " />
          <input
            ref={searchInputRef}
            type="text"
            className={`flex-grow focus:outline-none ${
              dark && "bg-gray-800 text-white"
            }`}
          />
        </div>

        <div className="flex flex-col w-1/4 space-y-2 justify-center mt-8">
          <button
            className={`btn ${dark && "bg-gray-900 text-white"}`}
            onClick={search}
          >
            Search
          </button>
        </div>
      </form>

      <footer
        className={`w-full divide-y-[1px] divide-gray-300 bg-gray-100 text-sm text-gray-500 ${
          dark && "bg-gray-900"
        }`}
      >
        <div
          className={` flex justify-center items-center text-gray-500 px-8 py-3 ${
            dark ? "hover:text-white" : "hover:text-black"
          }`}
        >
          <LocationMarkerIcon className="h-5 mr-2 " />
          <p>India</p>
        </div>
      </footer>
    </div>
  );
}
